### ISSUE TITLE
pet heal

### ISSUE THREAD

**Issue by Imna1975** [Vae2009/ConRO_Hunter#1]
since now for whatever reason everything is on a button like pet revive and pet heal so always comes the message that pet heal in the bar is missing yes sometimes it is there sometimes not none why can you turn off the 
![IMG_7927](https://user-images.githubusercontent.com/45740014/210179138-22d4c9e2-9de8-48a4-a3ae-0fa82f25360f.JPG)

**Comment by Vae2009** [comment]
Yes, the pet heal/revive spell is in your pet utilities but you can also drag it onto your bar. If you do not want to bring it onto your bar you can turn off this error message in the ConRO options menu.

**Comment by Imna1975** [comment]
looked again in the spellbook it is no longer but you can also heal with resurrect the pets
