### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by Imna1975** [Vae2009/ConRO_Hunter#3]
2x Usage: local configID = C_ClassTalents.GetLastSelectedSavedConfigID(specID)
[string "=[C]"]: in function `GetLastSelectedSavedConfigID'
[string "@ConRO/helper.lua"]:22: in function `CheckTalents'
[string "@ConRO/core.lua"]:2363: in function `EnableRotation'
[string "@ConRO/core.lua"]:2533: in function <ConRO/core.lua:2529>

Locals:
(*temporary) = "Usage: local configID = C_ClassTalents.GetLastSelectedSavedConfigID(specID)"

**Comment by Vae2009** [comment]
Ongoing talent system revisons.
